version: "3.0"

networks:
  ipfs:
    name: fabric_test
    external: true

volumes:
  ipfs_path:
  ipfs_staging:

services:
  ipfs.example.com:
    image: ipfs/kubo:latest
    container_name: ipfs.example.com
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/data/ipfs
    ports:
      - "4001:4001" # ipfs swarm
      #     - "4002:4002/udp" # udp swarm
      - "5001:5001" # expose if needed/wanted
      - "8080:8080" # exposes if needed/wanted
    volumes:
      - ipfs_staging:/export
      - ipfs_path:/data/ipfs
    networks:
      - ipfs
